=== amitsnyderman/sandwich-markup-language/sml.dtd
<!ELEMENT sandwich (bread|vegetable|fruit|meat|cheese|condiment|seasoning)+>
<!-- preparation: pressed? -->

<!ELEMENT bread (bread|vegetable|fruit|meat|cheese|condiment|seasoning)*>
<!ATTLIST bread
  type (sliced|roll|hero|bagel|englishmuffin|baguette|wrap) "sliced"
  variety CDATA #IMPLIED
  preparation (toasted|grilled) #IMPLIED
  thickness CDATA #IMPLIED
>

<!ELEMENT vegetable EMPTY>
<!ATTLIST vegetable
  type CDATA #REQUIRED
  variety CDATA #IMPLIED
  preparation CDATA #IMPLIED
  thickness CDATA #IMPLIED
>

<!ELEMENT fruit EMPTY>
<!ATTLIST fruit
  type CDATA #REQUIRED
  variety CDATA #IMPLIED
  preparation CDATA #IMPLIED
  thickness CDATA #IMPLIED
>

<!ELEMENT meat EMPTY>
<!ATTLIST meat
  type CDATA #REQUIRED
  variety CDATA #IMPLIED
  preparation CDATA #IMPLIED
  thickness CDATA #IMPLIED
>

<!ELEMENT cheese EMPTY>
<!ATTLIST cheese
  type CDATA #REQUIRED
  variety CDATA #IMPLIED
  preparation CDATA #IMPLIED
  thickness CDATA #IMPLIED
>

<!ELEMENT condiment EMPTY>
<!ATTLIST condiment
  type CDATA #REQUIRED
  variety CDATA #IMPLIED
  preparation CDATA #IMPLIED
  coverage CDATA #IMPLIED
>

<!ELEMENT seasoning EMPTY>
<!ATTLIST seasoning
  type CDATA #REQUIRED
  variety CDATA #IMPLIED
  coverage CDATA #IMPLIED
>

=== amitsnyderman/sandwich-markup-language/examples/cheesybagel.xml
<?xml version="1.0"?>
<!DOCTYPE sandwich SYSTEM "sml.dtd">

<!-- Cheesy Bagel Example -->
<sandwich>
	<cheese type="pepperjack" preparation="melted" />
	<vegetable type="tomato" thickness="thin" />
	<vegetable type="onion" variety="red" thickness="thin" />
	<seasoning type="zatar" coverage="sprinkled" />
	<cheese type="cream" variety="veggie" thickness="thin" />
	<vegetable type="olive" preparation="studded" />
	<bread type="bagel" variety="everything" preparation="toasted" />
</sandwich>
